### ISSUE TITLE
Update application footer

### ISSUE THREAD

**Issue by leochrisis** [projeto-spider/planning-poker#53]

**Comment by lubien** [comment]
[This line](https://github.com/projeto-spider/planning-poker/commit/707f6bd17b8c5b7d76f0caa94ef8420e831a759d#diff-82826061446b9e1535ed62e4c9f09daaR6) should be "Planning Poker by Projeto Spider".
"Planning Poker" should be a link to this repo.

**Comment by lubien** [comment]
Closed by c88e51874173252336ce54e566769ab2de3fe4d9
