### ISSUE TITLE
Is it running?

### ISSUE THREAD

**Issue by alexandre-mbm** [projeto-spider/planning-poker#70]
Are there screenshots?

**Comment by lubien** [comment]
@alexandre-mbm A major refactor of mine should have broke some things, but it works.

@leochrisis was working on a better README. He should put some screenshots soon.

**Comment by lubien** [comment]
@alexandre-mbm we have a demo [here](https://myspiderpp.herokuapp.com/#/dashboard) but keep in mind that not only there are missing features but also lacks some user experience optimization.

Expect the final product any time soon. I'll put the demo on the README (along with screenshots) when it happens, this link is just to satisfy your curiosity for now :).

**Comment by alexandre-mbm** [comment]
![captura de tela de 2017-09-04 19-22-30](https://user-images.githubusercontent.com/957501/30039388-73f72288-91a6-11e7-98bd-f97c5b383003.png)

**Comment by lubien** [comment]
Oh sorry I renamed the app and didn't update your link. [here](https://spider-poker.herokuapp.com/#/dashboard).

I must warn social login is not ready ready yet so just register normally.
